### ISSUE TITLE
Cannot enter mobile number for login

### ISSUE THREAD

**Issue by hrithikwins** [hrithikwins/bloodbank_app#17]
To reproduce
- Go to login screeen
- tap on the field that you see

Expected behaviour
- should be able to enter phone number in the field

Current behaviour
- not able to input anything nor it is clickable

**Comment by Keerthi-prasanna-Sa** [comment]
we need to create a row in the container and as children we need to add +91, sizedbox, Textfield for entering the code. This is the code for adding the TextField. With this we can enter the mobile number now.

Row(
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          Text(
                            "+91",
                            style: TextStyle(
                              fontSize: 20,
                              color: MyColors.redPrimary,
                            ),
                          ),
                          SizedBox(width: 25,),
                          Container(
                            width: 180,
                            child: TextField(
                              decoration: InputDecoration(
                              hintText: 'Enter you number here',
                            ),
                        ),
                          ),
                        ],
                      )
